[package]
name = "adventofcode"
version = "0.1.0"
authors = ["monarch"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
recap = "0.1.1"
regex = "1.4.2"
serde = "1.0.117"

[[examples]]
name = "day_1_a"
path = "src/examples/day_1/solution_a.rs"